### ISSUE TITLE
JWPlayer CDN URL has changed

### ISSUE THREAD

**Issue by scotthenley** [jshimko/meteor-jwplayer#1]
I think that JW Player has changed their CDN path as when I set up a new player (with a new account) the embed URL does not match up with what is in the package.

Currently in the package: script.src = 'https://jwpsrv.com/library/' + token + '.js';

The URL from JWPlayer: https://content.jwplatform.com/libraries/YOUR_KEY_HERE.js

I set up a local version of this package and adjusted the URL which got it working. Not sure if this is a JWPlayer version 6 vs 7  issue or not. I just set up my account to get the embed key.

**Comment by jshimko** [comment]
Of course they changed the URL for v7.  :)

So yeah, that's the v6 URL.  I guess I'll just have to maintain two branches and update the readme to point out which version to use.

Thanks for pointing that out!

**Comment by jshimko** [comment]
[Updated](https://github.com/jshimko/meteor-jwplayer/commit/749d2b9bf97609405e845719fc7c7256c8cbe6ca) and pushed to Atmosphere.

Give v7.0.1 of this package a test and let me know if you're all set.

**Comment by scotthenley** [comment]
Looks good now. Thanks!
